
name = "meave-example"
main = "dist/index.mjs"
compatibility_date = "2022-07-11"
compatibility_flags = ["streams_enable_constructors"]

[build]
command = "pnpm install && pnpm build"

[site]
bucket = "./dist/public"
